### ISSUE TITLE
stuck at "Processing..."

### ISSUE THREAD

**Issue by wheezy0** [DanielnetoDotCom/YouPHPTube-Encoder#3]
Trying to install this software to my debian apache2 server.
All requirements are satisfied, database created etc. No logs, I will have to dig into the php code to find the cause. Or if someone here can help..?
How do I debug this? I have double checked all fields several times, imported database manually using:
mysql -u tubeencoder -p tubeencoder -h mysql.domain.lan < database.sql with success, but still installation does not proceed.

**Comment by wheezy0** [comment]
trying to install manually.
From what I can see, videos/configuration.php has to get populated with values like this:
<?php
$global['webSiteRootURL'] = 'http://tube-encoder.domain.lan/';
$global['systemRootPath'] = '/var/www/YouPHPTube-Encoder';

$global['disableConfigurations'] = false;
$global['disableBulkEncode'] = false;

$mysqlHost = 'mysql.domain.lan';
$mysqlUser = 'tubeencoder';
$mysqlPass = 'h333333333333J&/t';
$mysqlDatabase = 'tubeencoder';

$global['allowed'] = array('mp4', 'avi', 'mov', 'mkv', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv');
/**
 * Do NOT change from here
 */

require_once \$global['systemRootPath'].'objects/include_config.php';

// END OF FILE

And I have to do some insert commands in mysql, then remove install directory. That's it?

**Comment by wheezy0** [comment]
// <?php
$global['webSiteRootURL'] = 'http://tube-encoder.domain.lan/';
$global['systemRootPath'] = '/var/www/YouPHPTube-Encoder';

$global['disableConfigurations'] = false;
$global['disableBulkEncode'] = false;

$mysqlHost = 'mysql.domain.lan';
$mysqlUser = 'tubeencoder';
$mysqlPass = 'p#n1yjfeowijfeowgfdKJ&/1';
$mysqlDatabase = 'tubeencoder';

$global['allowed'] = array('mp4', 'avi', 'mov', 'mkv', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv');
/**
 * Do NOT change from here
 */

require_once \$global['systemRootPath'].'objects/include_config.php';


// END OF FILE

And then some mysql inserts and remove install dir.

That's it?

**Comment by wheezy0** [comment]
How can I check if installation is in good shape?

**Comment by DanielnetoDotCom** [comment]
It is not a good idea to install it manually
The installation creates some registrations on the database 
If you create a configuration file and import the database sql it is not enough , try to install it from the installation script

**Comment by deivisonmoraes** [comment]
![screenshot_20170815_134753](https://user-images.githubusercontent.com/5691097/29326056-76ab4bbc-81c0-11e7-857c-239e8faf6f40.png)

Maybe this help us to found this problem. I my case, installation script not create a configuration file.

Tks

**Comment by deivisonmoraes** [comment]
In my case, not exists the configuration.php, I remove and git clone any times...

**Comment by deivisonmoraes** [comment]
XMLHttpRequest cannot load http://betavideos.com/login. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'IP of encoder' is therefore not allowed access.

Maybe this error can help us!

**Comment by deivisonmoraes** [comment]
After much research I gave up and reinstalled the streamer package, after reviewing it the encoder ran normally. I had already tested the encoder package before and there must have been some information that prevented a new installation. Now, the encoder finish installation!

**Comment by wheezy0** [comment]
Ended up installing manually. It did work.
had to do some inserts into database manually and create configuration.php with content manually. Just read the checkConfiguration.php file and do all the stuff manually.

**Comment by DanielnetoDotCom** [comment]
Sure

**Comment by DanielnetoDotCom** [comment]
I guess if your Streamer is an HTTPS it should work

**Comment by raj00565** [comment]
Same Issue I am facing Stuck in processing bar . let me know how to solve it .

**Comment by DanielnetoDotCom** [comment]
Raj do you have a link that I can check it?
I made some modifications today on encoder and streamer.
Update the files and see if it would works

**Comment by winklov** [comment]
can some help to get ffmpeg install on centos whm server

**Comment by raj00565** [comment]
use auto script to install streaming related all packages:

http://mirror.ffmpeginstaller.com/old/scripts/ffmpeg8/ffmpeginstaller.8.0.tar.gz

**Comment by winklov** [comment]
thank you can you please tell me how to install it please

**Comment by michaelday** [comment]
Figured out the problem. In the streamer, the Access-Control-Allow-Origin header is set by a .htaccess file, and wont work if you haven't enabled mod_headers. SSH into the machine the streamer is running on, and try the following:

```sh
a2enmod headers
service apache2 restart
```

The streamer site will start emitting the Access-Control-Allow-Origin header, and this should work as intended.

The main problem here is that the install page for the encoder does not respond properly to errors during the install, and the "Processing..." message will continue to display after a fatal error.

You can also reproduce this by providing a streamer url that is not a valid url, for example, "website". Because there is no `http://`, the browser will attempt to make a request to "website", which will throw an error in Chrome. The install page will not respond to this, and the "Processing..." message will continue to display.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by tgd1973** [comment]
Hello. Trying to install the encoder remains forever in processing ...
My system is a Centos 6.9 + Kloxo-mr. For the Streamer everything went well and works.
![error1](https://user-images.githubusercontent.com/15127860/34655434-f83bc646-f409-11e7-9211-ec7b580df71a.jpg)
![error2](https://user-images.githubusercontent.com/15127860/34655435-fb2d2ff2-f409-11e7-945a-d245631d0c93.jpg)

**Comment by DanielnetoDotCom** [comment]
I can see your streamer site is wrong, you need a streamer site installed before install the encoder

**Comment by tgd1973** [comment]
My site streamer is installed for 1 week, and it works ... I also wanted to install the encoder to no longer have problems with the thumbs for the mp4 ... If you want to give my address ... but not in public .. .

**Comment by DanielnetoDotCom** [comment]
Hi, I do not think it is a cross domain problem.
For example you can try to install with the demo site, and see if it works.
but is necessary that encoder can see the streamer. can you telnet streamer site domain from your encoder?

**Comment by tgd1973** [comment]
All two are on the same Centos + Kloxo-MR server ...
I do not think there's even a problem with telnet ... it's possible that it's something that the Centos or Kloxo has disabled for security ... but I do not understand what it is.

**Comment by tgd1973** [comment]
Was just what I thought problems related to the login streamer ... putting the link of your https://demo.youphptube.com/   installation was successful immediately.
But after entering the encoder panel, this error appeared ... obviously with obscuring them xxxzzz ...

Warning: file_get_contents(https://aaazzz.eu/plugin/CustomizeAdvanced/advancedCustom.json.php): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error in /home/xxx/zzzxxx.eu/view/index.php on line 176

Can you tell me what the problem would be?   On the telnet port 25 there is the Qmail mail server.

**Comment by DanielnetoDotCom** [comment]
We recommend for encoder at least a VPS, you will need root access to install some apps on the server

**Comment by tgd1973** [comment]
Thanks for the answer but how do I get a server and a VPS all the same on the same IP ... 
I have the optical fiber in the house Down1000/Upl200Mbps and this service I would like to do it as Home Hosting ...

**Comment by tgd1973** [comment]
Maybe I have the answer ... LAN DNS . I have a DrayTek Vigor 3900 which has the LAN DNS function.
I did a test to split by domain / subdomain ... and rout on another VPS on an internal ip ... and it works ... I do not know how stable a system like this.

**Comment by DanielnetoDotCom** [comment]
You can host at home, but you will need a linux installation.
If you host at home you will not need a VPS

**Comment by tgd1973** [comment]
My problem is that I have only one public IP - the ip from the line that is assigned to the shared server on which I already have 5 domains, Centos - Kloxo ... if I should use another Server just for Converter I do not have another IP to be assigned, if not private, which then will not be achievable from the outside ... Only thing I could do is use this Converter with another internal IP and to be ragoingibile also from outside I have to have a port for Apache other than 80 ... but then how can I use? the streamer on 80 and the Converter on 81? Definitely, it's not right ... because when I log in from the streamer on the encoder, he expects it to be there maybe 80 ... He has another idea ... Perhaps the best is to do the possibility to run the encoder even with Centos ... not just Ubuntu ... which then Centos is the enterprise clone copy of Redhat ... which is better than Ubuntu ....

**Comment by heymam2bab** [comment]
Hello @DanielnetoDotCom  we stay on the Processing screen when youphptube encoder is installed
 
we are getting errors like the screen below please help us?

https://user-images.githubusercontent.com/15127860/34655435-fb2d2ff2-f409-11e7-945a-d245631d0c93.jpg

We use cPanel centos 6

**Comment by DanielnetoDotCom** [comment]
Check apache error Log

**Comment by deaf-tv** [comment]
CentOs 7. 4 

CentOs Webpanel  CWP 
http://centos-webpanel.com/
Server CWP installed, CWP with FFMPEG Automat installed :-) 

PHP info
Server API: CGI/FastCGI
http://encoder.deaf-tv.eu/install/phpinfo.php

In order to use mod_rewrite you can type the following command in the terminal
http://encoder.deaf-tv.eu/install/index.php

/usr/loacl/apache/conf/httpd.conf
LoadModule rewrite_module modules/mod_rewrite.so
mod_rewrite on

Problem
Mod Rewrite is not enabled  <-- Not agrees

http://deaf-tv.eu/YouPHPTube/
YouPHPTube with htaccess
installed good


http://deaf-tv.eu/YouPHPTube-Encoder
YouPHPTube-Encoder with htaccess
installed good


http://deaf-tv.eu  
Clipbucket with htaccess  Videos all good

**Comment by DanielnetoDotCom** [comment]
@deaf-tv this does not say much about your problem

**Comment by DanielnetoDotCom** [comment]
BTW you can ignore the modrewrite error and install it

**Comment by deaf-tv** [comment]
Audio Music False ??  
deaf can not Audio Music

Videos good :-)

**Comment by DanielnetoDotCom** [comment]
We do not update audio feature for while, I will take a look on that again soon.

**Comment by deaf-tv** [comment]
Audio remove yes!

Videos with Feature and Unfeature

**Comment by DanielnetoDotCom** [comment]
@deaf-tv what?
